from turtle import *

speed(0)


def go(tup):
    goto(tup[0], tup[1])


def mark():
    dot(4, "black")


def changePenColor():
    pencolor('red')


def drawAmityAndWillow(x):
    W_HAIR_COLOR = '#344958'
    W_SHADE_HAIR_COLOR = '#2d3a46'
    W_SHADE_HAIR_COLOR_2 = '#1d2c36'
    W_SHADE_HAIR_COLOR_3 = '#131f29'
    W_FACE_COLOR = '#feeccb'
    W_FACE_SHADING_COLOR = '#a58e8f'
    W_GLASS_LINE_COLOR = '#dcba76'
    W_INNER_GLASS_COLOR = '#fafdfe'
    W_EYE_COLOR_1 = '#b7c8b1'
    W_EYE_COLOR_2 = '#d0e5c9'
    W_EYE_COLOR_3 = '#879c9e'
    W_EYE_COLOR_4 = '#e7f5f3'
    W_EYEBROW_COLOR = '#96a7b0'
    W_NOSE_COLOR = '#ccb1a6'
    W_RIGHT_EAR_COLOR = '#ddd1a5'
    W_HAIR_TIE_COLOR = '#1f6854'
    W_HAIR_TIE_SHADING_COLOR = '#1d3a3d'
    W_SHADED_SKIN_COLOR = '#c7b19b'
    W_SPELL_CIRCLE_LINE_COLOR = '#9af89f'
    W_SPELL_CIRCLE_FILL_COLOR = '#eafdda'
    W_INNER_SHIRT_COLOR = '#319172'
    W_OUTERMOST_SHIRT_COLOR = '#3b3542'
    W_OUTERMOST_SHIRT_SHADING_COLOR = '#23574e'
    W_SKIRT_COLOR = '#57535f'
    W_UPPER_SKIRT_SHADING_COLOR = '#211d2c'
    W_LOWER_SKIRT_SHADING_COLOR = '#373345'
    W_BELT_COLOR = '#353141'
    W_HAND_COLOR = '#fcebca'
    W_PANT_COLOR = '#3e8e75'
    W_PANT_SHADING_COLOR = '#295556'

    # helper functions
    def drawWillowEye():
        pd()
        startWRightOuterEye = pos()
        fillcolor(W_EYE_COLOR_1)
        begin_fill()
        seth(0)
        circle(0.32 * x)
        end_fill()

        circle(0.32 * x, 16)
        fillcolor(W_EYE_COLOR_2)
        begin_fill()
        pu()
        seth(120)
        circle(-0.33 * x, 40)
        rt(20)
        circle(-0.34 * x, 55)
        pd()
        rt(80)
        circle(-0.32 * x, 88)
        end_fill()

        pu()
        go(startWRightOuterEye)
        seth(90)
        fd(0.18 * x)
        pd()
        fillcolor(W_EYE_COLOR_3)
        begin_fill()
        seth(0)
        circle(0.14 * x)
        end_fill()

        pu()
        seth(135)
        fd(0.22 * x)
        pd()
        fillcolor(W_EYE_COLOR_4)
        begin_fill()
        seth(0)
        circle(0.1 * x)
        end_fill()

    # draw Willow's hair
    startWHair = pos()
    fillcolor(W_HAIR_COLOR)
    begin_fill()
    seth(110)
    circle(-2.4 * x, 60)
    rt(7)
    circle(-1.9 * x, 35)
    seth(12)
    fd(1.3 * x)
    rt(15)
    circle(1.4 * x, 59)
    rt(148)
    circle(-1.6 * x, 33)
    circle(-1.6 * x, -11)
    lt(126)
    circle(-2.3 * x, 61)
    rt(10)
    circle(-1.97 * x, 51)
    startWGlass = pos()
    seth(110)
    circle(1 * x, 100)
    rt(55)
    circle(-3.65 * x, 30)
    seth(-77)
    circle(2.2 * x, 33)
    circle(2.2 * x, -33)
    rt(26)
    circle(-2.55 * x, 35)
    rt(37)
    midWRightGlass = pos()
    circle(1.15 * x, 73)
    rt(35)
    circle(1.35 * x, 65)
    rt(142)
    circle(-1.3 * x, 55)
    go(startWHair)
    end_fill()

    # draw the shade in Willow's hair
    fillcolor(W_SHADE_HAIR_COLOR)
    begin_fill()
    seth(110)
    circle(-2.4 * x, 60)
    seth(246)
    pu()
    circle(3.3 * x, 43.3)
    pd()
    go(startWHair)
    end_fill()

    # draw Willow's face
    fillcolor(W_FACE_COLOR)
    begin_fill()
    seth(156)
    circle(0.55 * x, 63)
    preStartWEar = pos()
    lt(54)
    circle(1.7 * x, 51)
    startWLeftHairLower = pos()
    circle(1.7 * x, 39)
    circle(1.7 * x, -13)
    lt(13)
    circle(-0.8 * x, 79)
    startWFaceShading2 = pos()
    circle(-0.8 * x, 25)
    seth(11)
    circle(-0.6 * x, 52)
    seth(180)
    fd(0.4 * x)
    bk(0.2 * x)
    lt(148)
    circle(3.2 * x, 47)
    rt(8)
    circle(1.9 * x, 23)
    startWRightHair = pos()
    circle(1.9 * x, 39)
    lt(42)
    pu()
    circle(-3.2 * x, 49)
    pd()
    startWSpellCircleOuter = pos()
    go(startWGlass)
    seth(110)
    circle(1 * x, 100)
    rt(55)
    circle(-3.65 * x, 30)
    seth(-77)
    circle(2.2 * x, 33)
    circle(2.2 * x, -33)
    rt(26)
    circle(-2.55 * x, 35)
    rt(37)
    circle(1.15 * x, 73)
    rt(35)
    circle(1.35 * x, 65)
    rt(142)
    circle(-1.3 * x, 55)
    go(startWHair)
    end_fill()

    # draw ear
    pu()
    go(preStartWEar)
    seth(-15)
    fd(0.4 * x)
    seth(270)
    fd(0.1 * x)
    seth(180)
    fd(0.05 * x)
    pd()
    seth(-25)
    circle(-1.8 * x, 27)

    # draw Willow's face shading
    pu()
    go(preStartWEar)
    pd()
    fillcolor(W_FACE_SHADING_COLOR)
    begin_fill()
    seth(219)
    circle(0.55 * x, -11)
    pu()
    seth(283)
    circle(2.15 * x, 70)
    seth(279)
    fd(0.18 * x)
    pd()
    lt(40)
    circle(-0.8 * x, -23)
    lt(17)
    circle(1.7 * x, -85)
    end_fill()

    pu()
    go(startWFaceShading2)
    pd()
    begin_fill()
    seth(284)
    circle(-0.8 * x, 25)
    seth(11)
    circle(-0.6 * x, 52)
    seth(180)
    fd(0.2 * x)
    lt(148)
    circle(3.2 * x, 47)
    pu()
    seth(183)
    circle(-4.3 * x, 40.5)
    end_fill()

    # draw Willow's glass
    changePenColor()
    pu()
    go(startWGlass)
    pd()
    pencolor(W_GLASS_LINE_COLOR)
    fillcolor(W_INNER_GLASS_COLOR)
    begin_fill()
    seth(110)
    circle(1 * x, 100)
    rt(5)
    circle(1.2 * x, 86)
    startWGlassConnection1 = pos()
    circle(1.2 * x, 18)
    lt(39)
    pencolor('black')
    circle(-0.25 * x, -38)
    circle(-0.25 * x, 38)
    pencolor(W_GLASS_LINE_COLOR)
    circle(-0.25 * x, 142)
    pencolor('black')
    circle(-0.25 * x, -57)
    startWNose = pos()
    pencolor(W_GLASS_LINE_COLOR)
    lt(58)
    circle(1.3 * x, 62)
    pencolor('black')
    lt(72.5)
    pu()
    circle(-3.2 * x, 34)
    end_fill()

    pu()
    go(startWGlassConnection1)
    pd()
    pencolor(W_GLASS_LINE_COLOR)
    seth(160)
    circle(0.5 * x, 50)
    startWGlassConnection2 = pos()
    begin_fill()
    rt(132)
    circle(1.2 * x, 104)
    go(midWRightGlass)
    seth(185)
    circle(1.15 * x, 73)
    seth(260)
    circle(1.35 * x, 84)
    lt(10)
    circle(1.15 * x, 88)
    end_fill()

    # draw Willow's eye
    # right eye
    pencolor('black')
    pu()
    go(startWGlassConnection1)
    seth(67)
    fd(0.6 * x)
    pd()
    seth(74)
    circle(-0.5 * x, 140)
    lt(106)
    fd(0.3 * x)
    bk(0.3 * x)
    rt(106)
    lt(7)
    circle(-0.9 * x, 69)
    lt(5)
    circle(-0.42 * x, 127)

    pu()
    go(startWGlassConnection1)
    seth(-20)
    fd(0.5 * x)
    seth(270)
    fd(0.05 * x)
    drawWillowEye()

    # left eye
    pu()
    go(startWGlassConnection2)
    seth(113)
    fd(0.8 * x)
    seth(270)
    fd(0.05 * x)
    pd()
    seth(122)
    circle(0.6 * x, 132)
    rt(106)
    fd(0.3 * x)
    bk(0.3 * x)
    lt(97)
    circle(0.9 * x, 59)
    circle(0.6 * x, 113)

    pu()
    go(startWGlassConnection2)
    seth(196)
    fd(1 * x)
    seth(0)
    fd(0.1 * x)
    seth(270)
    fd(0.05 * x)
    pd()
    drawWillowEye()

    # draw Willow's eyebrow
    # right
    pu()
    go(startWGlassConnection1)
    seth(52)
    fd(1.65 * x)
    pd()
    fillcolor(W_EYEBROW_COLOR)
    begin_fill()
    seth(208)
    circle(-1.4 * x, 25)
    lt(3)
    circle(0.08 * x, 190)
    rt(3)
    circle(1.1 * x, 35)
    end_fill()

    # left
    pu()
    go(startWGlassConnection2)
    seth(135)
    fd(1.8 * x)
    seth(90)
    fd(0.05 * x)
    pd()
    begin_fill()
    seth(332)
    circle(1.4 * x, 25)
    rt(3)
    circle(-0.08 * x, 190)
    lt(3)
    circle(-1.1 * x, 35)
    end_fill()

    # draw Willow's nose
    pu()
    go(startWNose)
    seth(263)
    fillcolor(W_NOSE_COLOR)
    begin_fill()
    pd()
    circle(-0.25 * x, 57)
    pu()
    seth(180)
    fd(0.05 * x)
    rt(42 - 60)
    circle(-0.08 * x, 150)
    go(startWNose)
    end_fill()

    # draw Willow's mouth
    pu()
    go(startWGlassConnection1)
    seth(283)
    fd(1.3 * x)
    pd()
    seth(203)
    circle(-1 * x, 64)
    lt(70)
    circle(-0.42 * x, -27)
    circle(-0.42 * x, 65)
    
    # draw Willow's upper spell circle
    pu()
    go(startWSpellCircleOuter)
    seth(62)
    pd()
    pencolor(W_SPELL_CIRCLE_LINE_COLOR)
    pensize(2)
    fillcolor(W_SPELL_CIRCLE_FILL_COLOR)
    begin_fill()
    circle(-3.2 * x)
    end_fill()
    pu()
    rt(90)
    fd(0.2 * x)
    lt(90)
    pd()
    fillcolor('white')
    begin_fill()
    circle(-3 * x)
    end_fill()

    # draw Willow's right ear
    pu()
    pensize(1)
    pencolor('black')
    go(startWSpellCircleOuter)
    seth(-72)
    fd(0.34 * x)
    pd()
    fillcolor(W_RIGHT_EAR_COLOR)
    begin_fill()
    seth(38)
    circle(-0.75 * x, 52)
    rt(76)
    circle(-2.1 * x, 34)
    rt(110)
    circle(1.5 * x, 25.3)
    startWHairInsideCircle = pos()
    pu()
    rt(72)
    circle(-3 * x, 2)
    rt(42.3)
    pd()
    fd(0.7 * x)
    bk(0.7 * x)
    pu()
    lt(42.3)
    circle(-3 * x, 10)
    end_fill()

    # draw part of Willow's hair inside the circle
    pu()
    go(startWHairInsideCircle)
    pd()
    fillcolor(W_HAIR_COLOR)
    begin_fill()
    seth(151.3)
    circle(1.5 * x, -100.5)
    pu()
    lt(73)
    circle(-3 * x, 45)
    end_fill()

    pu()
    circle(-3 * x, -45)
    pd()
    begin_fill()
    seth(8)
    circle(-0.25 * x, 120)
    pu()
    rt(117)
    circle(-3 * x, 9)
    end_fill()

    # draw Willow's hand inside circle
    circle(-3 * x, -9)
    pd()
    fillcolor(W_INNER_SHIRT_COLOR)
    begin_fill()
    seth(69)
    fd(0.9 * x)
    startWLeftHand = pos()
    rt(55)
    circle(-0.8 * x, 68)
    seth(268)
    fd(1.3 * x)
    rt(110)
    circle(-3 * x, 27)
    end_fill()

    pu()
    go(startWLeftHand)
    fillcolor(W_HAND_COLOR)
    begin_fill()
    pd()
    seth(14)
    circle(-0.8 * x, 68)
    seth(11)
    fd(0.7 * x)
    rt(26)
    fd(0.8 * x)
    rt(6)
    circle(0.23 * x, 180)
    seth(159)
    fd(0.8 * x)
    rt(102)
    circle(0.5 * x, -16)
    circle(0.5 * x, 76)
    rt(72)
    circle(0.5 * x, 65)
    rt(81)
    bk(0.15 * x)
    fd(0.95 * x)
    rt(17)
    circle(0.23 * x, 210)
    seth(204)
    fd(0.8 * x)
    circle(-1.6 * x, 38)
    seth(82)
    fd(0.2 * x)
    rt(8)
    circle(0.85 * x, 55)
    lt(9)
    circle(0.18 * x, 110)
    seth(276)
    circle(-1.6 * x, 40)
    go(startWLeftHand)
    end_fill()

    # draw the lower part of Willow's hair
    # main part
    pu()
    go(startWLeftHairLower)
    fillcolor(W_HAIR_COLOR)
    begin_fill()
    pd()
    seth(324)
    circle(1.7 * x, 26)
    lt(13)
    circle(-0.8 * x, 79)
    circle(-0.8 * x, 25)
    seth(11)
    circle(-0.6 * x, 52)
    seth(180)
    fd(0.2 * x)
    lt(148)
    startShadingOval = pos()
    circle(3.2 * x, 5)
    startWShirtBehindHand = pos()
    seth(-63)
    circle(-0.45 * x, 27)
    circle(-1.2 * x, 90)
    circle(-0.45 * x, 90)
    seth(104)
    circle(-1.4 * x, 33)
    startWHairTie = pos()
    seth(150)
    circle(-1.3 * x, 85)
    end_fill()

    # shading the oval part
    pu()
    go(startShadingOval)
    fillcolor(W_SHADE_HAIR_COLOR_2)
    begin_fill()
    pd()
    seth(328)
    circle(3.2 * x, 5)
    seth(-63)
    circle(-0.45 * x, 27)
    circle(-1.2 * x, 90)
    circle(-0.45 * x, 90)
    pu()
    rt(5)
    circle(-1.2 * x, 95)
    end_fill()

    # draw Willow's hair tie
    pu()
    go(startWHairTie)
    pd()
    fillcolor(W_HAIR_TIE_COLOR)
    begin_fill()
    seth(90)
    circle(-0.6 * x, 135)
    seth(165)
    circle(0.9 * x, 79)
    end_fill()

    # side shading
    pu()
    go(startWLeftHairLower)
    pd()
    fillcolor(W_SHADE_HAIR_COLOR)
    begin_fill()
    seth(324)
    circle(1.7 * x, 9)
    seth(255)
    pu()
    circle(1.2 * x, 64)
    pd()
    seth(57)
    circle(-0.6 * x, -33)
    go(startWHairTie)
    seth(150)
    circle(-1.3 * x, 85)
    end_fill()

    pu()
    go(startWHairTie)
    pd()
    fillcolor(W_HAIR_TIE_SHADING_COLOR)
    begin_fill()
    seth(90)
    circle(-0.6 * x, 33)
    seth(319)
    pu()
    circle(1.2 * x, 7)
    pd()
    seth(218)
    circle(0.9 * x, 20)
    end_fill()

    pu()
    go(startWHairTie)
    pd()
    fillcolor(W_SHADE_HAIR_COLOR_2)
    begin_fill()
    seth(241)
    circle(0.9 * x, -20.5)
    seth(251)
    pu()
    circle(1.5 * x, 21)
    pd()
    lt(148)
    circle(-1.2 * x, -25)
    startWHairOvalShading = pos()
    seth(104)
    circle(-1.4 * x, 33)
    end_fill()

    pu()
    go(startWHairOvalShading)
    pd()
    fillcolor(W_SHADE_HAIR_COLOR_3)
    begin_fill()
    seth(85)
    circle(-1.2 * x, 25)
    seth(272)
    pu()
    circle(1.5 * x, 40)
    pd()
    rt(127)
    circle(-1.2 * x, 4)
    circle(-0.45 * x, 90)
    end_fill()

    # draw Willow's shirt part behind the hand
    pu()
    go(startWShirtBehindHand)
    pd()
    fillcolor(W_OUTERMOST_SHIRT_COLOR)
    begin_fill()
    seth(333)
    circle(3.2 * x, 42)
    seth(-12)
    circle(-0.8 * x, 61)
    rt(107)
    circle(-8.9 * x, 5)
    rt(18)
    circle(3.4 * x, 36.5)
    startWOutermostShirt = pos()
    lt(58)
    circle(-1.2 * x, -18.5)
    circle(-0.45 * x, -27)
    end_fill()

    # draw Willow's right hair
    # main part
    pu()
    go(startWRightHair)
    pd()
    fillcolor(W_HAIR_COLOR)
    begin_fill()
    seth(30)
    circle(1.9 * x, 39)
    lt(42)
    pu()
    circle(-3.2 * x, -23.2)
    pd()
    seth(239)
    circle(2.7 * x, 14)
    rt(66)
    circle(-8.9 * x, 8.8)
    seth(95)
    circle(-1.7 * x, 28)
    end_fill()
    
    # shading
    pu()
    go(startWRightHair)
    pd()
    fillcolor(W_SHADE_HAIR_COLOR_2)
    begin_fill()
    seth(30)
    circle(1.9 * x, 10)
    rt(147)
    pu()
    circle(0.85 * x, 74)
    pd()
    rt(145)
    circle(-8.9 * x, 4.7)
    preStartWRightHairShading2 = pos()
    seth(95)
    circle(-1.7 * x, 28)
    end_fill()

    pu()
    go(preStartWRightHairShading2)
    seth(177.3)
    circle(-8.9 * x, -6.3)
    startWRightHairShading2 = pos()
    pd()
    begin_fill()
    circle(-8.9 * x, -2.4)
    lt(66)
    circle(2.7 * x, -12)
    pu()
    go(startWRightHairShading2)
    end_fill()

    # hair tie
    go(startWRightHair)
    seth(30)
    circle(1.9 * x, 24)
    fillcolor(W_HAIR_TIE_COLOR)
    begin_fill()
    pd()
    startWRightHairTie = pos()
    circle(1.9 * x, 6)
    rt(28)
    circle(-0.2 * x, 90)
    rt(4)
    pu()
    circle(3.2 * x, 2)
    pd()
    go(startWRightHairTie)
    end_fill()
    
    pu()
    go(startWRightHair)
    pd()
    fillcolor(W_SHADED_SKIN_COLOR)
    begin_fill()
    seth(67)
    circle(-1.7 * x, -27)
    seth(-73)
    circle(-0.8 * x, -60)
    seth(7)
    circle(1.9 * x, 23)
    end_fill()

    pu()
    go(startWOutermostShirt)
    fillcolor(W_OUTERMOST_SHIRT_COLOR)
    begin_fill()
    pd()
    seth(193.5)
    circle(3.4 * x, -36.5)
    lt(18)
    circle(-8.9 * x, -4)
    startWShirtLeftSleeve = pos()
    seth(243)
    circle(-5.2 * x, 57)
    startWUpperSkirt = pos()
    rt(92)
    circle(-4.8 * x, 27)
    lt(120)
    startWUpperSkirtShading = pos()
    circle(-1.2 * x, -64)
    end_fill()

    # draw Willow's left shirt sleeve
    # main part
    pu()
    go(startWShirtLeftSleeve)
    fillcolor(W_INNER_SHIRT_COLOR)
    begin_fill()
    pd()
    seth(177.5)
    circle(-8.9 * x, -9.8)
    seth(253)
    circle(2.7 * x, -14)
    lt(75.3)
    pu()
    circle(3.2 * x, 25)
    pd()
    startWShirtLeftSleeveShading = pos()
    seth(272)
    circle(-1.9 * x, 39)
    rt(30)
    circle(-6.8 * x, 34)
    lt(50)
    circle(-5.2 * x, -24.5)
    end_fill()

    # draw Willow's upper part of the skirt
    pu()
    go(startWUpperSkirt)
    fillcolor(W_SKIRT_COLOR)
    begin_fill()
    pd()
    seth(186)
    circle(-5.2 * x, -32.3)
    seth(169)
    circle(-6.8 * x, -22.5)
    seth(270)
    circle(-1.8 * x, 44)
    startWRightWrist = pos()
    circle(-1.8 * x, 8)
    rt(47.5)
    circle(24 * x, 11)
    end_fill()

    # draw Willow's belt
    fillcolor(W_BELT_COLOR)
    begin_fill()
    seth(181.5)
    circle(24 * x, -11)
    seth(265)
    fd(0.5 * x)
    rt(74)
    fd(0.6 * x)
    rt(25.2)
    circle(14 * x, 16.3)
    startWLowerSkirt = pos()
    seth(100)
    circle(-4.8 * x, 6)
    end_fill()

    # draw Willow's lower part of the skirt
    pu()
    go(startWLowerSkirt)
    fillcolor(W_SKIRT_COLOR)
    begin_fill()
    pd()
    seth(182.1)
    circle(14 * x, -16.3)
    lt(25.2)
    bk(0.6 * x)
    lt(76)
    circle(5.8 * x, 16)
    startWLowerSpellCircle = pos()
    circle(5.8 * x, 16)
    rt(100)
    circle(-8.2 * x, 40)
    startWLeftLeg = pos()
    lt(3)
    fd(1.25 * x)
    rt(91)
    circle(-11.4 * x, 12)
    lt(6)
    circle(-2.65 * x, 21)
    end_fill()

    # draw Willow's right hand
    # wrist
    pu()
    go(startWRightWrist)
    fillcolor(W_INNER_SHIRT_COLOR)
    begin_fill()
    pd()
    seth(226)
    circle(-1.8 * x, 8)
    seth(265)
    fd(0.5 * x)
    startWRightWristShading = pos()
    lt(2)
    circle(5.8 * x, 5)
    seth(-10)
    fd(1 * x)
    lt(45)
    circle(0.7 * x, 78)
    startWRightHand = pos()
    go(startWRightWrist)
    end_fill()

    # wrist shading
    pu()
    go(startWRightWristShading)
    fillcolor(W_OUTERMOST_SHIRT_SHADING_COLOR)
    begin_fill()
    pd()
    seth(267)
    circle(5.8 * x, 5)
    seth(-10)
    fd(1 * x)
    lt(45)
    circle(0.7 * x, 20)
    startWRightHandShading = pos()
    pu()
    go(startWRightWristShading)
    end_fill()

    # hand
    go(startWRightHand)
    fillcolor(W_FACE_COLOR)
    begin_fill()
    pd()
    seth(113)
    circle(0.7 * x, -78)
    rt(109)
    circle(0.5 * x, 124)
    rt(27)
    circle(-0.9 * x, 31)
    lt(14)
    circle(0.2 * x, 180)
    lt(4)
    fd(0.3 * x)
    seth(49)
    fd(0.45 * x)
    rt(21)
    fd(1 * x)
    circle(0.2 * x, 180)
    fd(0.9 * x)
    bk(0.7 * x)
    rt(20)
    fd(0.25 * x)
    lt(10)
    fd(0.5 * x)
    bk(0.5 * x)
    rt(10)
    fd(0.5 * x)
    go(startWRightHand)
    end_fill()

    pu()
    go(startWRightHandShading)
    fillcolor(W_FACE_SHADING_COLOR)
    begin_fill()
    pd()
    seth(55)
    circle(0.7 * x, -20)
    rt(109)
    circle(0.5 * x, 124)
    rt(27)
    circle(-0.9 * x, 31)
    lt(14)
    circle(0.2 * x, 180)
    fd(0.1 * x)
    seth(213)
    pu()
    circle(-1.1 * x, 57)
    end_fill()

    # draw Willow's lower spell circle
    pu()
    go(startWLowerSpellCircle)
    fillcolor(W_SPELL_CIRCLE_FILL_COLOR)
    pensize(2)
    pencolor(W_SPELL_CIRCLE_LINE_COLOR)
    begin_fill()
    seth(283)
    circle(5.8 * x, 5)
    pd()
    seth(-41)
    circle(3.1 * x, 218)
    pu()
    lt(90)
    circle(-1.9 * x, 6)
    seth(180)
    fd(0.1 * x)
    seth(0)
    circle(-2.9 * x, 2.5)
    pd()
    circle(-2.9 * x, 223)
    end_fill()
    pensize(1)
    pencolor('black')

    # shading for the skirt
    pu()
    go(startWUpperSkirtShading)
    fillcolor(W_UPPER_SKIRT_SHADING_COLOR)
    begin_fill()
    pd()
    seth(187)
    circle(-1.2 * x, -23)
    seth(256)
    pu()
    circle(8.35 * x, 19.9)
    pd()
    rt(96)
    circle(14 * x, 2.3)
    startWLowerSkirtShading = pos()
    seth(100)
    circle(-4.8 * x, 33)
    end_fill()

    pu()
    go(startWLowerSkirtShading)
    fillcolor(W_LOWER_SKIRT_SHADING_COLOR)
    begin_fill()
    pd()
    seth(182.2)
    circle(14 * x, -2.3)
    seth(231)
    pu()
    circle(6.2 * x, 32.3)
    pd()
    seth(162)
    fd(0.8 * x)
    rt(91)
    circle(-11.4 * x, 12)
    lt(6)
    circle(-2.65 * x, 21)
    end_fill()

    # shading for the upper sleeve
    pu()
    go(startWShirtLeftSleeveShading)
    pd()
    fillcolor(W_OUTERMOST_SHIRT_SHADING_COLOR)
    begin_fill()
    seth(272)
    circle(-1.9 * x, 39)
    rt(30)
    circle(-6.8 * x, 34)
    lt(50)
    circle(-5.2 * x, -7)
    pu()
    seth(-13)
    circle(5 * x, 30)
    rt(10)
    circle(1.55 * x, 67)
    end_fill()

    # redraw missing part after the shading
    pu()
    go(startWUpperSkirt)
    pd()
    seth(181.5)
    circle(24 * x, -11)
    circle(24 * x, 11)
    seth(186)
    circle(-5.2 * x, -57)

    # draw Willow's leg
    # left
    pu()
    go(startWLeftLeg)
    fillcolor(W_PANT_COLOR)
    begin_fill()
    pd()
    seth(159)
    circle(-8.2 * x, -17.5)
    seth(258)
    fd(2.8 * x)
    seth(180)
    fd(2.2 * x)
    rt(87.5)
    circle(-11.1 * x, 17)
    end_fill()

    fillcolor(W_PANT_SHADING_COLOR)
    begin_fill()
    seth(159)
    circle(-8.2 * x, -4)
    seth(252)
    pu()
    circle(8.1 * x, 22.1)
    seth(180)
    pd()
    fd(0.5 * x)
    rt(87.5)
    circle(-11.1 * x, 17)
    end_fill()

    # right
    pu()
    go(startWLeftLeg)
    seth(159)
    circle(-8.2 * x, -21)
    mark()
    fillcolor(W_PANT_COLOR)
    begin_fill()
    pd()
    circle(-8.2 * x, -15.7)
    seth(-73)
    fd(3.2 * x)
    seth(180)
    fd(2 * x)
    rt(60)
    circle(-11.5 * x, 15)
    end_fill()

    fillcolor(W_PANT_SHADING_COLOR)
    begin_fill()
    seth(180)
    circle(-8.2 * x, -1.7)
    seth(-64)
    pu()
    fd(2.77 * x)
    seth(-75)
    fd(0.3 * x)
    pd()
    seth(180)
    fd(0.38 * x)
    rt(60)
    circle(-11.5 * x, 15)
    end_fill()

    ht()
    print(pos())
    print(heading())


pu()
goto(-150, 150)
pd()
drawAmityAndWillow(35)
done()
